pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Copy Artifact to Ansible Server') {
            steps {
                sshagent(['ansible-ssh-key']) {
                    sh '''
                    scp -o StrictHostKeyChecking=no target/*.jar ec2-user@<Ansible-EC2-IP>:/home/ec2-user/deploy/
                    '''
                }
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sshagent(['ansible-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ec2-user@<Ansible-EC2-IP> "ansible-playbook /home/ec2-user/deploy/deploy.yml"
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Build, artifact transfer, and deployment completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs for details.'
        }
    }
}

